### ISSUE TITLE
Exiting the Customizer causes issues in the Admin bar

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/style-manager#5]
When I enter the Customizer while viewing a specific page and then press the X (exit) button, the page URL contains some new text elements and the following happen:

- some options from the Admin bar dissapear (like the Edit page button)

https://user-images.githubusercontent.com/53944294/127298062-af4ad22e-6c3e-4128-b1be-c15e4f2fa564.mp4

- pressing the Customize button again seems to generate an Error

https://user-images.githubusercontent.com/53944294/127298092-6633f7cb-60bf-4354-b621-5492a609e212.mp4

This happens only when I have the Style Manager plugin activated and seems to happen regardles of the active theme. I tested using Tw-Tw-One and the same thing happened.

**Comment by georgeolaru** [comment]
@andreiungurianu I encountered the same issue in the past few weeks, and I thought it's related to my local environment. 

@vladolaru, can you take a look to see if it's something that we could prevent?
