### ISSUE TITLE
Can't reorder/nest Menu Items from Customizer

### ISSUE THREAD

**Issue by andreiungurianu** [pixelgrade/style-manager#6]
I can't seem to be able to nest or properly reorder Menu Items from the Customizer while I have the Style Manager plugin active. This is how it looks like:

https://user-images.githubusercontent.com/53944294/127298660-adaebbb8-21e9-4724-9b53-41ab7dbbfd4b.mp4

When I deactivate it, everything is back to normal. I'm using Style Manager 2.0.4

**Comment by georgeolaru** [comment]
Thanks for reporting @andreiungurianu! 

There seems to be a styling conflict from Style Manager with the  – @madalingorbanescu can you take a look over this?

**Comment by madalingorbanescu** [comment]
Fixed in https://github.com/pixelgrade/style-manager/pull/8
