### ISSUE TITLE
Critical error when activating plugin due to incompatible Carbon Fields

### ISSUE THREAD

**Issue by jggerrits** [pixelgrade/style-manager#7]
Sorry, the attached image is in Dutch, but I think you can understand the message. I used Customify and need to upgrade to Style Manager.

After activating the plugin, the /wp-admin can no longer be reached and needs to be recovered in recovery mode.

Got this from the apache logs:

----
[Wed Jul 28 10:43:05.876072 2021] [proxy_fcgi:error] [pid 25494:tid 139890356279040] [client 185.58.53.95:51060] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Pixelgrade\\StyleManager\\Provider\\PluginSettingsCFDatastore::load($field) must be compatible with Carbon_Fields\\Datastore\\Datastore_Interface::load(Carbon_Fields\\Field\\Field $field) in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/style-manager/src/Provider/PluginSettingsCFDatastore.php on line 12\n',
-----

![Carbon_Fields](https://user-images.githubusercontent.com/1236111/127307089-cde4bd2b-76b1-4413-b5fd-93b499010422.jpeg)

**Comment by vladolaru** [comment]
Thank you @jggerrits for this report. To help me nail down the problem, could you share **a list of active plugins** and also **the PHP version** your server is using? Thanks.

**Comment by jggerrits** [comment]
WordPress 5.8
Server running PHP version: 7.0.16.

List of plugins:
---
business-profile
coming-soon
customify
display-php-version
duplicate-page
food-and-drink-menu
fsp-premium-helper
nova-blocks
pixelgrade-care
restaurant-reservations
style-manager
temporary-login-without-password
ultimate-addons-for-gutenberg
updraftplus
wordpress-seo
wp-google-maps
wp-mail-smtp
wp-restaurant-manager
wpforms-lite

**Comment by vladolaru** [comment]
Thank you @jggerrits for your info. I have fixed the issue and will release an update shortly.
